# Note: This file is generated by the 'vec_2_fucntion#' Generated Topic Palette 
#' #' @export 
topic_palette <- function() { 
 
# Palette colors 
pal <- c('#9BA19D', '#0B3563', '#FCFCFC', '#B67B4F', '#D8D8D7', '#257942', '#BBE80C', '#00219F', '#FAFAFB', '#9EA3A7', '#E3CD9E', '#A0A5A9', '#C61A0A', '#888687', '#6D6F68', '#731011', '#593A27', '#EFCB38', '#AA802F', '#9FBBAB', '#9B9959', '#E2CB9D', '#FB8919', '#958A73', '#0256BF', '#5A92DA', '#5F74A1', '#F7F084', '#37ADBE', '#B21104', '#227742', '#C81B0A', '#FCFCFE', '#6E6E5C', '#FB97AB', '#E2ACC8', '#A5A9B2', '#CA6198', '#572A12', '#625E51') 
topic_names <- c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40') 
names(pal) <- topic_names 
pal 
}